### ISSUE TITLE
Couldn't find the saved models

### ISSUE THREAD

**Issue by onurboyar** [by256/icsg3d#46]
Hello,

thanks for sharing your work. I was able to replicate your environment by using Python 3.7, and I am currently training the unet model. 

(there was an issue with the pymatgen version, I used the 2023 version of pymatgen for data_query part)

However, it looks like training will take quite a long time. 

In the repo, you write the following information for the location of saved models

saved_models/unet/mode/unet_weights_mode.h5 saved_models/unet/mode/class_weights.npy saved_models/vae/mode/vae_weights_mode.hdf5 saved_models/cgcnn/

however, it seems the saved models are not available in the repository. Would it be possible to access them?

**Comment by cjcourt** [comment]
Hi @onurboyar , in #22 I think @by256 made the models available in Google Drive, [here](https://drive.google.com/file/d/1MTWl34Jp0io2dDcvRGOkESkrO6Vns8Pf/view?usp=sharing) (you may need to request access).

Thanks
CC

**Comment by onurboyar** [comment]
Thank you very much for prompt response, I sent access request
