### ISSUE TITLE
Issue generating new samples

### ISSUE THREAD

**Issue by marcoloco23** [by256/icsg3d#5]
Great work, this is really exciting. However, I am having trouble generating new samples using the pre-trained models as I get the following value error when running a command such as "python3 generate.py --name perovskites --nsamples 1000 --base CeCrO3 --var 0.5": 

ValueError: Shape must be rank 5 but is rank 4 for '{{node lambda/Tile}} = Tile[T=DT_FLOAT, Tmultiples=DT_INT32](Placeholder, lambda/Tile/multiples)' with input shapes: [?,1,1,1,10], [4].

It seems to be a problem with the encoder model of the LatticeDFCVAE class.

Do you know what the cause of this could be and how it could be fixed? Thanks

**Comment by by256** [comment]
Hi - thanks for the interest.

The example command you provided works for me and I'm unable to reproduce the error you're getting. Could you check that you are using tensorflow==2.1.0 and Keras==2.3.1?

If you are using these versions and are still running into this error, please let me know.

Batuhan

**Comment by marcoloco23** [comment]
Yes that seemed to do the trick. Thank you
